---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.tugboat.cloudrasayan.com
  resources:
  - broadcastjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.tugboat.cloudrasayan.com
  resources:
  - broadcastjobs/finalizers
  verbs:
  - update
- apiGroups:
  - apps.tugboat.cloudrasayan.com
  resources:
  - broadcastjobs/status
  verbs:
  - get
  - patch
  - update
