apiVersion: apps.tugboat.cloudrasayan.com/v1
kind: BroadcastJob
metadata:
  labels:
    app.kubernetes.io/name: broadcastjob
    app.kubernetes.io/instance: broadcastjob-sample
    app.kubernetes.io/part-of: tugboat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tugboat
  name: hello-world-broadcastjob
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: helloworld
          image: hello-world
  # restartLimit: 3 #number of retry allowed for each node
  labels:
    kubernetes.io/hostname: microk8s-vm
  nodeSelector:
    kubernetes.io/os: linux
  cleanupafter: 30s




