apiVersion: apps.tugboat.cloudrasayan.com/v1
kind: BroadcastJob
metadata:
  labels:
    app.kubernetes.io/name: broadcastjob
    app.kubernetes.io/instance: broadcastjob-sample
    app.kubernetes.io/part-of: tugboat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tugboat
  name: broadcastjob-sample
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: [ "perl", "-Mbignum=bpi", "-wle", "print bpi(2000)" ]
  restartLimit: 3 #number of retry allowed for each node




